[phases.setup]
nixPkgs = ["nodejs", "nodePackages.npm", "chromium"]

[phases.install]
cmds = [
  "npm ci",
  "npx playwright install chromium",
  "npx playwright install-deps chromium",
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"